# Generated by Django 5.2.10 on 2026-01-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        ('website', '0004_projectpage_mecc_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=64)),
                ('icon_class', models.CharField(default='fas fa-building', max_length=64)),
            ],
            options={
                'verbose_name': 'إحصائية',
                'verbose_name_plural': 'إحصاءات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeTimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon_class', models.CharField(default='fas fa-file-search', max_length=64)),
            ],
            options={
                'verbose_name': 'خطوة عمل',
                'verbose_name_plural': 'خطوات العمل',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon_class', models.CharField(default='fas fa-shield-alt', max_length=64)),
            ],
            options={
                'verbose_name': 'ميزة ثقة',
                'verbose_name_plural': 'ميزات الثقة',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'رأي عميل',
                'verbose_name_plural': 'آراء العملاء',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='شركة سمر قند للمقاولات', max_length=255)),
                ('brand_title', models.CharField(default='سمر قند', max_length=64)),
                ('brand_subtitle', models.CharField(blank=True, max_length=255)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('founders', models.TextField(blank=True)),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_1', models.CharField(blank=True, max_length=64)),
                ('phone_2', models.CharField(blank=True, max_length=64)),
                ('fax', models.CharField(blank=True, max_length=64)),
                ('topbar_slogan', models.CharField(blank=True, max_length=255)),
                ('footer_about', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_line_1', models.CharField(default='شركة سمر قند', max_length=255)),
                ('hero_title_line_2', models.CharField(default='للمقاولات', max_length=255)),
                ('hero_lead', models.CharField(default='نبني أحلامك بأيدٍ فلسطينية ماهرة', max_length=255)),
                ('hero_primary_cta_label', models.CharField(default='ابدأ مشروعك الآن', max_length=64)),
                ('hero_primary_cta_url', models.CharField(blank=True, max_length=255)),
                ('hero_secondary_cta_label', models.CharField(default='تعرّف على خدماتنا', max_length=64)),
                ('hero_secondary_cta_url', models.CharField(default='#services', max_length=255)),
                ('newsletter_title', models.CharField(default='اشترك في نشرتنا الإخبارية', max_length=255)),
                ('newsletter_subtitle', models.CharField(default='احصل على آخر العروض والنصائح الهندسية مباشرة على بريدك', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'عضو فريق',
                'verbose_name_plural': 'فريق العمل',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
