# Generated by Django 5.2.10 on 2026-01-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0005_homestat_hometimelinestep_hometrustbadge_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAIFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('badge_text', models.CharField(default='AI', max_length=16)),
            ],
            options={
                'verbose_name': 'ميزة AI',
                'verbose_name_plural': 'ميزات AI',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeAIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'مؤشر AI',
                'verbose_name_plural': 'مؤشرات AI',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
