# Generated by Django 5.2.10 on 2026-01-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0006_homeaifeature_homeaimetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
