# Generated by Django 5.2.10 on 2026-01-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_aicontentgeneratorpage_aidesignanalyzerpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='gemini_api_key_env_var',
            field=models.CharField(default='GEMINI_API_KEY', max_length=64),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='gemini_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='gemini_model',
            field=models.CharField(default='gemini-1.5-flash', max_length=64),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='max_output_tokens',
            field=models.PositiveIntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='visualizer_default_aspect_ratio',
            field=models.CharField(default='16:9', max_length=8),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='visualizer_default_style',
            field=models.CharField(default='modern', max_length=32),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='visualizer_placeholder_footer_text',
            field=models.CharField(default='تصور تجريبي • سمر قند', max_length=255),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='visualizer_placeholder_primary_hex',
            field=models.CharField(default='#4A90E2', max_length=7),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='visualizer_placeholder_secondary_hex',
            field=models.CharField(default='#5DADE2', max_length=7),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='electric_unit_price_ils',
            field=models.FloatField(default=22.0),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='plumbing_unit_price_ils',
            field=models.FloatField(default=18.0),
        ),
    ]
