# Generated by Django 5.2.10 on 2026-01-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0009_aisettings_gemini_api_key_env_var_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'اعتماد/ترخيص',
                'verbose_name_plural': 'اعتمادات وتراخيص',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
