# Generated by Django 5.2.10 on 2026-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_companycertification'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='chamber_membership',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='registration_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='CompanyCertification',
        ),
    ]
