# Generated by Django 5.2.10 on 2026-01-24 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('website', '0011_companysettings_chamber_membership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisibilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_services', models.BooleanField(default=True)),
                ('show_projects', models.BooleanField(default=True)),
                ('show_tools', models.BooleanField(default=True)),
                ('show_showcase', models.BooleanField(default=True)),
                ('show_team', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('show_home_trust_badges', models.BooleanField(default=True)),
                ('show_home_stats', models.BooleanField(default=True)),
                ('show_home_timeline', models.BooleanField(default=True)),
                ('show_newsletter', models.BooleanField(default=True)),
                ('show_ai_chatbot', models.BooleanField(default=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
