# Generated by Django 5.2.10 on 2026-01-25 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_sitevisibilitysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('template_key', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='ILS', max_length=8)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب عرض سعر (RFQ)',
                'verbose_name_plural': 'طلبات عروض الأسعار (RFQ)',
                'ordering': ['-id'],
            },
        ),
    ]
