# Generated by Django 5.2.10 on 2026-01-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_sitevisibilitysettings_more_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatorsettings',
            name='contingency_percent',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='currency_default',
            field=models.CharField(default='ILS', max_length=3),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='include_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='overhead_percent',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='profit_percent',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='usd_to_ils_rate',
            field=models.FloatField(default=3.65),
        ),
        migrations.AddField(
            model_name='calculatorsettings',
            name='vat_percent',
            field=models.FloatField(default=0.16),
        ),
    ]
