# Generated by Django 5.2.10 on 2026-01-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_calculatorsettings_contingency_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='status',
            field=models.CharField(choices=[('ongoing', 'قيد العمل'), ('completed', 'منجز')], default='completed', max_length=20),
        ),
    ]
