# Generated by Django 5.2.10 on 2026-01-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_projectpage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='key_deliverables',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='key_risks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='key_stakeholders',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='management_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='pmp_phase',
            field=models.CharField(choices=[('initiating', 'البدء (Initiating)'), ('planning', 'التخطيط (Planning)'), ('executing', 'التنفيذ (Executing)'), ('monitoring', 'المتابعة والتحكم (Monitoring & Controlling)'), ('closing', 'الإغلاق (Closing)')], default='planning', max_length=30),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='scope_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='target_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
