# Generated by Django 5.2.10 on 2026-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_projectpage_budget_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisibilitysettings',
            name='show_control_projects_management',
            field=models.BooleanField(default=True),
        ),
    ]
