# Generated by Django 5.2.10 on 2026-01-28 12:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_sitevisibilitysettings_show_control_projects_management"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectpage",
            name="status",
            field=models.CharField(
                choices=[
                    ("ongoing", "قيد العمل"),
                    ("completed", "منجز"),
                    ("archived", "مؤرشف"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
    ]

