# Generated by Django 5.2.10 on 2026-01-30 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('website', '0021_client_equipment_inventoryitem_subcontractor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('template', 'قوالب'), ('letterhead', 'ترويسات'), ('invoice', 'فواتير'), ('receipt', 'سندات قبض'), ('company_document', 'مستندات الشركة'), ('company_certificate', 'وثائق الشركة')], max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مستند الشركة',
                'verbose_name_plural': 'مستندات الشركة',
                'ordering': ['category', 'sort_order', 'id'],
            },
        ),
    ]
