# Generated by Django 5.2.10 on 2026-01-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_companydocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['name', 'id'], 'verbose_name': 'موظف/عامل', 'verbose_name_plural': 'الموظفون/العمال'},
        ),
        migrations.AddField(
            model_name='worker',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='kind',
            field=models.CharField(choices=[('worker', 'عامل'), ('employee', 'موظف')], default='worker', max_length=16),
        ),
        migrations.AddField(
            model_name='worker',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='WorkerPayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('salary', 'راتب'), ('advance', 'سلفة'), ('bonus', 'مكافأة'), ('deduction', 'خصم')], default='salary', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='website.worker')),
            ],
            options={
                'verbose_name': 'دفعة رواتب',
                'verbose_name_plural': 'دفعات الرواتب',
                'ordering': ['-year', '-month', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('half_day', 'نصف يوم'), ('leave', 'إجازة')], default='present', max_length=16)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_attendance', to='website.projectpage')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='website.worker')),
            ],
            options={
                'verbose_name': 'دوام',
                'verbose_name_plural': 'الدوام',
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('worker', 'date'), name='uniq_worker_attendance_per_day')],
            },
        ),
    ]
