# Generated by Django 5.2.10 on 2026-01-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0023_alter_worker_options_worker_active_worker_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="time_clock_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, unique=True
            ),
        ),
    ]

