# Generated by Django 5.2.10 on 2026-01-31 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_worker_time_clock_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsPermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('allowed_roles', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'قاعدة صلاحية',
                'verbose_name_plural': 'قواعد الصلاحيات',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='workerattendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerattendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerattendance',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerattendance',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerattendance',
            name='state',
            field=models.CharField(choices=[('draft', 'مسودة'), ('review', 'قيد المراجعة'), ('approved', 'معتمد'), ('locked', 'مقفول')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='workerpayrollentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerpayrollentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workerpayrollentry',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerpayrollentry',
            name='source',
            field=models.CharField(choices=[('manual', 'يدوي'), ('auto_attendance', 'تلقائي من الدوام')], default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='workerpayrollentry',
            name='source_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerpayrollentry',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('paid', 'مدفوع')], default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='OpsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, max_length=32)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OpsTimeclockImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(choices=[('manual', 'يدوي'), ('folder', 'مجلد')], default='manual', max_length=16)),
                ('dry_run', models.BooleanField(default=False)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='website.projectpage')),
            ],
            options={
                'verbose_name': 'استيراد ساعة دوام',
                'verbose_name_plural': 'استيرادات ساعة الدوام',
                'ordering': ['-id'],
            },
        ),
    ]
